// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Generates tailored recommendations for improving customer movement through the pirate funnel.
 *
 * - generateRecommendations - A function that generates recommendations based on customer persona and funnel stage.
 * - GenerateRecommendationsInput - The input type for the generateRecommendations function.
 * - GenerateRecommendationsOutput - The return type for the generateRecommendations function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';
import {CustomerPersona} from '@/services/customer-persona';

const GenerateRecommendationsInputSchema = z.object({
  customerPersona: z.object({
    id: z.string().describe('The unique identifier for the customer persona.'),
    name: z.string().describe('The name of the customer persona.'),
    description: z.string().describe('A brief description of the customer persona.'),
    attributes: z.record(z.any()).describe('Other relevant attributes for the customer persona.'),
  }).describe('The customer persona to generate recommendations for.'),
  funnelStage: z.string().describe('The current stage of the pirate funnel (Acquisition, Activation, Retention, Referral, Revenue).'),
});
export type GenerateRecommendationsInput = z.infer<typeof GenerateRecommendationsInputSchema>;

const GenerateRecommendationsOutputSchema = z.object({
  recommendations: z.array(z.string()).describe('A list of AI-powered recommendations tailored to the customer persona and funnel stage.'),
});
export type GenerateRecommendationsOutput = z.infer<typeof GenerateRecommendationsOutputSchema>;

export async function generateRecommendations(input: GenerateRecommendationsInput): Promise<GenerateRecommendationsOutput> {
  return generateRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateRecommendationsPrompt',
  input: {
    schema: z.object({
      customerPersona: z.object({
        id: z.string().describe('The unique identifier for the customer persona.'),
        name: z.string().describe('The name of the customer persona.'),
        description: z.string().describe('A brief description of the customer persona.'),
        attributes: z.record(z.any()).describe('Other relevant attributes for the customer persona.'),
      }).describe('The customer persona to generate recommendations for.'),
      funnelStage: z.string().describe('The current stage of the pirate funnel (Acquisition, Activation, Retention, Referral, Revenue).'),
    }),
  },
  output: {
    schema: z.object({
      recommendations: z.array(z.string()).describe('A list of AI-powered recommendations tailored to the customer persona and funnel stage.'),
    }),
  },
  prompt: `You are a marketing expert specializing in optimizing customer funnels for METRO AG.
  Based on the customer persona and their current stage in the pirate funnel, provide a list of recommendations to improve their movement to the next stage.

  Customer Persona:
  Name: {{{customerPersona.name}}}
  Description: {{{customerPersona.description}}}
  Attributes: {{{JSON.stringify(customerPersona.attributes)}}}

  Funnel Stage: {{{funnelStage}}}

  Recommendations:`, // Ensure this is valid Handlebars syntax.
});

const generateRecommendationsFlow = ai.defineFlow<
  typeof GenerateRecommendationsInputSchema,
  typeof GenerateRecommendationsOutputSchema
>({
  name: 'generateRecommendationsFlow',
  inputSchema: GenerateRecommendationsInputSchema,
  outputSchema: GenerateRecommendationsOutputSchema,
}, async input => {
  const {output} = await prompt(input);
  return output!;
});
